name: Generate Vercel Branch Preview URL
description: Generate the branch preview URL for a Vercel deployment
branding:
  icon: link
  color: purple
inputs:
  vercel-team-id:
    description: Vercel team ID
    required: true
  vercel-project-name:
    description: Vercel project name
    required: true
  git-branch-name:
    description: Branch name
    required: true
runs:
  using: node20
  main: index.js
